version: '3'
services:
  jlab:
    build:
      context: ./py3
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: Asia/Tokyo
    tty: true
    command: 
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    expose:
      - '8888'
    ports:
      - '8888:8888'
    volumes:
      - ./py3/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
    working_dir: /workspace
